### ISSUE TITLE
Pretty-printed output format?

### ISSUE THREAD

**Issue by beaugunderson** [nevillegrech/gigahorse-toolchain#11]
Hi there--I've been familiarizing myself with gigahorse and haven't been able to find out how to enable the type of analysis described in the paper:

> Gigahorse produces output both in structured form (i.e., tables, exported as CSV files) and in pretty-printed text.

I can successfully generate the tables/CSVs but haven't been able to figure out how to generate the pretty-printed text output format. I'm hoping to produce output similar to contract-library.com to aid in my own analysis (the contracts in question are on the Matic sidechain unfortunately or I'd just use contract-library itself).

Appreciate the work that's been put into gigahorse; I've currently been limping by with panoramix.

**Comment by beaugunderson** [comment]
Ah, I see `get_source.py` and the source decompiler in the [artifact from the paper on Zenodo](https://zenodo.org/record/2578692#.XVJC7S1L08Y). Have updates been released to it anywhere, or will there be?

**Comment by yanniss** [comment]
Sorry, we have not publicly released source decompiler versions after the paper artifact and it's still in the non-public codebase. But if this is a non-commercial application perhaps we can work something out.

**Comment by beaugunderson** [comment]
Definitely non-commercial, this is just me looking at how things work to satisfy my curiosity. :)

**Comment by nevillegrech** [comment]
Might be great to get Polygon smart contracts on contract-library but haven't tried that yet. Can we connect to Polygon via web3 and call standard web3 calls like `getCode(<address>)` or `getBlock(<block_number>)` ?

**Comment by beaugunderson** [comment]
Yup! Just need to use the Matic-specific RPC, everything else works
identically though.

**Comment by beaugunderson** [comment]
You can use the public endpoints:

- https://rpc-mainnet.maticvigil.com/
- https://rpc-mainnet.matic.quiknode.pro/
- https://matic-mainnet.chainstacklabs.com/
- https://matic-mainnet-full-rpc.bwarelabs.com/
- https://matic-mainnet-archive-rpc.bwarelabs.com/
- https://rpc-mainnet.matic.network/
- wss://rpc-mainnet.maticvigil.com/ws
- wss://rpc-mainnet.matic.quiknode.pro/
- wss://ws-matic-mainnet.chainstacklabs.com/
- wss://matic-mainnet-full-ws.bwarelabs.com/
- wss://matic-mainnet-archive-ws.bwarelabs.com/
- wss://ws-mainnet.matic.network/

Or you can get a user-specific RPC endpoint here which has higher limits, it currently only requires an email address (they offer paid tiers with even higher limits though):

https://rpc.maticvigil.com/

Let me know if there's anything I can do to help in this regard, happy to put some time toward the contract scraping effort.

**Comment by HikariShine** [comment]
I have this question too, My code on the bsc network, so i can't use contract library do decompiled the bytecode,  have some plan to support it?

**Comment by sifislag** [comment]
You can now decompile contracts on networks not supported by contract-library using the on demand decompilation feature: https://library.dedaub.com/decompile
Closing this issue.
