### ISSUE TITLE
Running Gigahorse Manually: Cannot open fact file MaxContextDepth.csv

### ISSUE THREAD

**Issue by XiaowenHu96** [nevillegrech/gigahorse-toolchain#13]
I was trying to run Gigahorse manually by directly invoking souffle with the facts generated by `generatefacts`.
However, I ran into an error complaining about missing `MaxContextDepth.csv` as input.

Am I missing something here? I'm using the latest Souffle release 2.0.2

**Comment by sifislag** [comment]
Hi,
`MaxContextDepth` is an optional input to gigahorse overriding the maximum context depth of its transactional context sensitivity. If it is not found the decompilation continues with the maximum context depth defaulting to 8.
