### ISSUE TITLE
Result differs when running Gigahorse manually

### ISSUE THREAD

**Issue by XiaowenHu96** [nevillegrech/gigahorse-toolchain#17]
I tried to run the Gigahorse pipeline manually with the instructions given in readme (with `MaxContextDepth.csv` set to 8)

I then compare them with the results generated from `gigahorse.py` using `diff -qr out .temp/long_running/out | sort` and notice

1. Some files are different. E.g.
```
Files out/ActualReturnArgs.csv and .temp/long_running/out/ActualReturnArgs.csv differ
Files out/FormalArgs.csv and .temp/long_running/out/FormalArgs.csv differ
Files out/Function.csv and .temp/long_running/out/Function.csv differ
...
```

2. There are two extra files produced from running manually
```
Only in out: Fail.csv
Only in out: Helper_Zeros.csv
```
`Fail.csv` is an empty file. 
`Helper_Zeros.csv` contains:
```
	0
0	1
00	2
000	3
0000	4
00000	5
000000	6
0000000	7
00000000	8
000000000	9
0000000000	10

```

3. Some files only exists when running from `gigahorse.py`
```
Only in .temp/long_running/out: Verbatim_CDLAllVSStaticVSArr.csv
Only in .temp/long_running/out: Verbatim_MemConsStmtsLengths.csv
...
```

I do not see any error or warning when running the pipeline manually. Could it simply be a misconfiguration? Let me know if you need the full log.

**Comment by yanniss** [comment]
gigahorse.py now does 4 rounds of inlining by default before it attempts decompilation. So, some functions disappear and the code is generally altered significantly. To get identical results when running the toolchain manually you have to compile the inliner and apply it, or to use the flag --disable-inline in the gigahorse.py execution. Look for "inline" in the gigahorse.py code to find the relevant parts.

**Comment by XiaowenHu96** [comment]
Ah! I see! Thanks for the answer.
