### ISSUE TITLE
cannot run the example

### ISSUE THREAD

**Issue by smartcontract-detect-yzu** [nevillegrech/gigahorse-toolchain#26]
I run the example, and some error happened as following:

root@cj-YangTianM4000e-17:/home/cj/Work/PONZI/gigahorse-toolchain# ./gigahorse.py examples/long_running.hex
Compiling /home/cj/Work/PONZI/gigahorse-toolchain/logic/main.dl to C++ program and executable
Compiling /home/cj/Work/PONZI/gigahorse-toolchain/clientlib/function_inliner.dl to C++ program and executable
Error: syntax error, unexpected <, expecting end of file in unknown source location.
1 errors generated, evaluation aborted
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "./gigahorse.py", line 287, in compile_datalog
    assert not(process.returncode), "Compilation failed. Stopping."
AssertionError: Compilation failed. Stopping.
Error: syntax error, unexpected (, expecting . in unknown source location.
1 errors generated, evaluation aborted
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "./gigahorse.py", line 287, in compile_datalog
    assert not(process.returncode), "Compilation failed. Stopping."
AssertionError: Compilation failed. Stopping.
Traceback (most recent call last):
  File "./gigahorse.py", line 542, in <module>
    open(v, 'r') # check program exists
FileNotFoundError: [Errno 2] No such file or directory: '/home/cj/Work/PONZI/gigahorse-toolchain/logic/main.dl_compiled'

**Comment by iliastsa** [comment]
What souffle version are you using?

**Comment by SillyTin** [comment]
I use the souffle 2.0.2 and have the same issue.

**Comment by SillyTin** [comment]
Here is my console output

```bash
~/projects/ethereum_decompiler# ./gigahorse-toolchain/gigahorse.py /root/projects/ethereum_decompiler/1/target/target.bin
Process Process-1:
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "./gigahorse-toolchain/gigahorse.py", line 272, in compile_datalog
    preproc_process = subprocess.run(preproc_command, universal_newlines=True, capture_output=True)
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "./gigahorse-toolchain/gigahorse.py", line 272, in compile_datalog
    preproc_process = subprocess.run(preproc_command, universal_newlines=True, capture_output=True)
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
Traceback (most recent call last):
  File "./gigahorse-toolchain/gigahorse.py", line 542, in <module>
    open(v, 'r') # check program exists
FileNotFoundError: [Errno 2] No such file or directory: '/root/projects/ethereum_decompiler/gigahorse-toolchain/logic/main.dl_compiled'
```

**Comment by iliastsa** [comment]
@SillyTin Seems like you are using Python 3.6, however Gigahorse requires Python 3.8+.

**Comment by SillyTin** [comment]
Ok...The output changes....But only "[]" in results.json.

```
~/projects/ethereum_decompiler# python3.8 ./gigahorse-toolchain/gigahorse.py /root/projects/ethereum_decompiler/1/target/target.bin
Compiling /root/projects/ethereum_decompiler/gigahorse-toolchain/logic/main.dl to C++ program and executable
Compiling /root/projects/ethereum_decompiler/gigahorse-toolchain/clientlib/function_inliner.dl to C++ program and executable
Processing contract names.
Setting up workers.
Analysing...


Finished 0 contracts...


Writing results to results.json
```

**Comment by SillyTin** [comment]
Here is the hex in _target.bin_.

`608060405234801561001057600080fd5b50600436106100415760003560e01c80632966c024146100465780638da5cb5b14610050578063af0699c51461006e575b600080fd5b61004e61008c565b005b610058610126565b6040516100659190610193565b60405180910390f35b61007661014c565b60405161008391906101c7565b60405180910390f35b600160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff161461011c576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040161011390610265565b60405180910390fd5b6020600081905550565b600160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b60005481565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b600061017d82610152565b9050919050565b61018d81610172565b82525050565b60006020820190506101a86000830184610184565b92915050565b6000819050919050565b6101c1816101ae565b82525050565b60006020820190506101dc60008301846101b8565b92915050565b600082825260208201905092915050565b7f546869732066756e6374696f6e206973207265737472696374656420746f207460008201527f686520636f6e74726163742773206f776e657200000000000000000000000000602082015250565b600061024f6033836101e2565b915061025a826101f3565b604082019050919050565b6000602082019050818103600083015261027e81610242565b905091905056fea264697066735822122055f7ea7d421124372424c00aa277a0ba77efea02b5e0a703043124c465e04dbf64736f6c63430008090033`

**Comment by iliastsa** [comment]
By default, gigahorse only accepts `.hex` files. You can either rename your file to `target.hex`, or add the `-p` flag to make gigahorse accept `.bin` files as follows: `python3.8 gigahorse.py -p .*\.bin /root/projects/ethereum_decompiler/1/target/target.bin`

**Comment by SillyTin** [comment]
ohhh GREAT! It works. Thanks!

**Comment by metrocoding** [comment]
same issue I use python@3.8 and souffle@2.0.2
