### ISSUE TITLE
Can't compile contract

### ISSUE THREAD

**Issue by metrocoding** [nevillegrech/gigahorse-toolchain#28]
I install it properly but it throws an error during compile:
```
#34 0.355 Compiling /home/reviewer/gigahorse-toolchain/logic/main.dl to C++ program and executable
#34 0.360 Compiling /home/reviewer/gigahorse-toolchain/clientlib/function_inliner.dl to C++ program and executable
#34 403.6 compiler error: cannot compile source file /home/reviewer/gigahorse-toolchain/cache/69422d6108360eb40049666acc113122.cpp
#34 403.6 g++ -std=c++17   -fwrapv  -DUSE_NCURSES  -O3 -DUSE_LIBZ  -DUSE_SQLITE  -fopenmp  -march=native  -std=c++17 -Wdate-time -D_FORTIFY_SOURCE=2 -o/home/reviewer/gigahorse-toolchain/cache/69422d6108360eb40049666acc113122 /home/reviewer/gigahorse-toolchain/cache/69422d6108360eb40049666acc113122.cpp  -ldl -lpthread -lsqlite3 -lz -lncurses -lfunctors  -I/usr/bin/../include -I/usr/bin/include 
#34 403.6 g++: internal compiler error: Killed (program cc1plus)
#34 403.6 Please submit a full bug report,
#34 403.6 with preprocessed source if appropriate.
#34 403.6 See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
#34 403.7 failed to compile C++ source </home/reviewer/gigahorse-toolchain/cache/69422d6108360eb40049666acc113122.cpp>
#34 403.9 Process Process-2:
#34 403.9 Traceback (most recent call last):
#34 403.9   File "/usr/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
#34 403.9     self.run()
#34 403.9   File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
#34 403.9     self._target(*self._args, **self._kwargs)
#34 403.9   File "/home/reviewer/gigahorse-toolchain/gigahorse.py", line 287, in compile_datalog
#34 403.9     assert not(process.returncode), "Compilation failed. Stopping."
#34 403.9 AssertionError: Compilation failed. Stopping.
#34 500.4 Traceback (most recent call last):
#34 500.4   File "/home/reviewer/gigahorse-toolchain/gigahorse.py", line 542, in <module>
#34 500.4     open(v, 'r') # check program exists
#34 500.4 FileNotFoundError: [Errno 2] No such file or directory: '/home/reviewer/gigahorse-toolchain/clientlib/function_inliner.dl_compiled'
```

**Comment by metrocoding** [comment]
By comparison, Panoramix gives a partial decompilation but fails to function unknown35904722

**Comment by iliastsa** [comment]
Seems like the C++ compiler got killed, most likely due to running out of memory: `g++: internal compiler error: Killed (program cc1plus)`

**Comment by metrocoding** [comment]
> Seems like the C++ compiler got killed, most likely due to running out of memory: `g++: internal compiler error: Killed (program cc1plus)`. Try running it wit the `--interpreted` flag - it will be slower, but it skips compilation.

thanks, it is actually worked.
but still a problem. I got these files (image below) after decompiling
how to get something like this: #12 code user @sifislag shared?
<img width="516" alt="Screen Shot 2022-01-08 at 1 24 01 AM" src="https://user-images.githubusercontent.com/46874334/148612779-17af28fb-3142-45b0-a726-843099af5396.png">

**Comment by sifislag** [comment]
Hi, the gigahorse client that provides the source-like output is not open source. If you point me to the contract's address I can play around with a few settings to get a good decompilation output and send it to you here or via email if you prefer.

**Comment by metrocoding** [comment]
> Hi, the gigahorse client that provides the source-like output is not open source. If you point me to the contract's address I can play around with a few settings to get a good decompilation output and send it to you here or via email if you prefer.

thanks, sir:
https://bscscan.com/address/0xF00F86665200DAf40A387bb4B9FD597045244217#code
it would be great is you help me with this: [email](mailto:dead4game@live.com)

**Comment by jenningstodd** [comment]
Hi, I got the same issue and am now able to get results by adding the `--interpreted` option thanks to @iliastsa, but also not able to get a source-like output. Could you help me with [`0x5ce908a6ffb393e9cb88dd8d6e8594a6a14a0b60` at BSC](https://bscscan.com/address/0x5ce908a6ffb393e9cb88dd8d6e8594a6a14a0b60) ([email](mailto:jenningstodd@yandex.com)) / is there any plan to make the source-like-output part available? Many thanks!

**Comment by sifislag** [comment]
On demand decompilation has been added to contract-library: https://library.dedaub.com/decompile
Closing this issue.
