### ISSUE TITLE
Why is the compiled file incomplete?

### ISSUE THREAD

**Issue by lwy0518** [nevillegrech/gigahorse-toolchain#53]
My souffle version is 2.1, and the file opened after running command "gigahorse-toolchain/gigahorse.py -C detector2.dl examples/long_running.hex" has very little content. The result is as follows:
![image](https://user-images.githubusercontent.com/72444130/198823531-478e6c97-2ec9-461c-8184-35b0f002c684.png)
![image](https://user-images.githubusercontent.com/72444130/198823475-1ea8053e-fd64-47cb-b163-7be9f94156a3.png)

Why not get complete data? Looking forward to your reply, thank you very much!

**Comment by sifislag** [comment]
Hi,
Can you share the console output of `gigahorse.py`?
Also you can try with souffle 2.3 and see if that makes a difference.
Lastly it looks like the output is for a file named SimpleDAO and not long_running.

**Comment by lwy0518** [comment]
First of all, thank you very much for your reply!
Hi, sifis，I'm sorry. It may be that there is a problem with the compiled bytecode. I tried a file named long_runnig and the result is complete. But I have another question.There are many outputs(``.output``) A file named ``detector2.dl``,  but after running the command(``gigahorse-toolchain/gigahorse.py -C detector2.dl  examples/long_running.hex``) sometimes these outputs are displayed and sometimes not. How can I solve this problem?
![image](https://user-images.githubusercontent.com/72444130/199014556-e2bcebe9-0daf-4964-91f4-85bf1d4de2e5.png)
![image](https://user-images.githubusercontent.com/72444130/199014634-1fd596fd-8329-45e0-aa76-40170fe07884.png)
Looking forward to your reply！

**Comment by sifislag** [comment]
Can you show me what gigahorse prints to the console in both cases (when outputs are missing and when they're there)?

**Comment by lwy0518** [comment]
For distinction, all output results start with ``Vul_``, but looking at a file named ``.temp/long_running/out/`` does not have these.
![image](https://user-images.githubusercontent.com/72444130/199028092-8671b6bc-a054-448a-ae6d-e26a75b9e29d.png)
![image](https://user-images.githubusercontent.com/72444130/199028150-40ff6ac8-0fce-4b2d-a466-0ce49c3df709.png)
![image](https://user-images.githubusercontent.com/72444130/199028194-9026216f-92fa-453a-962e-25e7a1916c6c.png)
