### ISSUE TITLE
,

### ISSUE THREAD

**Issue by woods1060** [nevillegrech/gigahorse-toolchain#6]

**Comment by iliastsa** [comment]
Have you installed and configured the requirements correctly? This seems like something goes wrong during the souffle invocation.

**Comment by nevillegrech** [comment]
Can you paste the entire console output?

**Comment by woods1060** [comment]
`./gigahorse.py examples/long_running.hex
Compiling /home/janson/giga-test/gigahorse-toolchain-master/logic/decompiler.dl to C++ program and executable
compiler error: cannot compile source file /home/janson/giga-test/gigahorse-toolchain-master/cache/505048e6322550ec4484abd9ec12821a.cpp
g++ -std=c++17   -fwrapv  -DUSE_NCURSES  -O3 -DUSE_LIBZ  -DUSE_SQLITE  -fopenmp  -march=native  -std=c++17 -Wdate-time -D_FORTIFY_SOURCE=2 -o/home/janson/giga-test/gigahorse-toolchain-master/cache/505048e6322550ec4484abd9ec12821a /home/janson/giga-test/gigahorse-toolchain-master/cache/505048e6322550ec4484abd9ec12821a.cpp  -ldl -lpthread -lsqlite3 -lz -lncurses -lfunctors  -I/usr/bin/../include -I/usr/bin/include 
/usr/bin/ld: 找不到 -lfunctors
collect2: error: ld returned 1 exit status
failed to compile C++ source </home/janson/giga-test/gigahorse-toolchain-master/cache/505048e6322550ec4484abd9ec12821a.cpp>
Process Process-1:
Traceback (most recent call last):
  File "/home/janson/.pyenv/versions/3.8.2/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/janson/.pyenv/versions/3.8.2/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "./gigahorse.py", line 198, in compile_datalog
    assert not(process.returncode), "Compilation failed. Stopping."
AssertionError: Compilation failed. Stopping.
Traceback (most recent call last):
  File "./gigahorse.py", line 387, in <module>
    open(v, 'r') # check program exists
FileNotFoundError: [Errno 2] No such file or directory: 'decompiler_compiled'
`
thank you for your response,i dont know how to dedug

**Comment by nevillegrech** [comment]
I think b52e55d98e849eeb6020c08e1287f440865eae41 should also help prevent this from accidentally happening.
