### ISSUE TITLE
A problem of "souffle-addon"?

### ISSUE THREAD

**Issue by lwy0518** [nevillegrech/gigahorse-toolchain#67]
Hello! I have installed souffle-2.3 and downloaded gigahorse, but then I entered the "souffle-addon" and executed the command "make -j8", and the following error occurred:
![image](https://user-images.githubusercontent.com/72444130/218386268-ed555511-f6ea-4ee1-bf91-a4a989957587.png)
![image](https://user-images.githubusercontent.com/72444130/218386310-c6387053-9304-445c-a999-d07ffd60bb9f.png)
What is the reason for this problem? Looking forward to your reply. Thanks!

**Comment by sifislag** [comment]
Hi, can you also try using the 2.3 release version? Haven't had the same issue.

**Comment by lwy0518** [comment]
Hi, the souffle version I installed is currently 2.3.

**Comment by sifislag** [comment]
It looks like a development version following the 2.3 release.
For example when I run the `souffle --version` command I get this:
```
----------------------------------------------------------------------------
Version: 2.3
----------------------------------------------------------------------------
Copyright (c) 2016-22 The Souffle Developers.
Copyright (c) 2013-16 Oracle and/or its affiliates.
All rights reserved.
============================================================================
```

**Comment by lwy0518** [comment]
I re-downloaded the souffle-2.3 installation package, and the results displayed after the installation are as follows:
![image](https://user-images.githubusercontent.com/72444130/218448057-dd08b4b8-5c52-4772-96ca-bd6024eec78e.png)
