### ISSUE TITLE
Warning: Variable newContext only occurs once in file transactional-context.dl at line 113

### ISSUE THREAD

**Issue by darkn0mad** [nevillegrech/gigahorse-toolchain#8]

**Comment by darkn0mad** [comment]
Can not run on Ubuntu 18.04, all dependencies are met.


FAILED (errors=1)
root@localhost:~/gigahorse-toolchain# ./run_tests.sh
Warning: Variable newContext only occurs once in file transactional-context.dl at line 113
MergeContext(ctx, caller, newContext) :-
--------------------------^--------------
Warning: No rules/facts defined for relation StorageContents in file decompiler_output.dl at line 73
.decl StorageContents(addr: symbol, contents: symbol)
------^-----------------------------------------------
Warning: No rules/facts defined for relation SHA3Decompositions in file decompiler_output.dl at line 76
.decl SHA3Decompositions(addr: symbol, base1: symbol, base2: symbol, offset: symbol)
------^------------------------------------------------------------------------------
cannot find user-defined operator `hex_to_number`
souffle: ./include/souffle/utility/MiscUtil.h:195: void souffle::fatal(const char*, const Args& ...) [with Args = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >}]: Assertion `false && "fatal error; see std err"' failed.

======================================================================
ERROR: test_relation_size_approx (src.test.decompilation_size_test.DecompilationSizeTest) (test_case=TestCase(bytecode_path='/root/gigahorse-toolchain/tests/core-decompiler/rubus-token-0x876/0x876a11639ce3d2bba1712fc9f47bd6faee575ad4.hex', blocks=431, jump_to_many=1, poly_target=0, poly_target_same_ctx=0))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/gigahorse-toolchain/src/test/decompilation_size_test.py", line 30, in test_relation_size_approx
    sizes = self.extract_relation_size(decompilation, self.relation_names)
  File "/root/gigahorse-toolchain/src/test/decompilation_size_test.py", line 42, in extract_relation_size
    with open(f'{decompilation.out_dir}/{relation}') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/root/gigahorse-toolchain/src/test/utils/../.temp/0x876a11639ce3d2bba1712fc9f47bd6faee575ad4/out//Analytics_Blocks.csv'

----------------------------------------------------------------------
Ran 1 test in 3.568s

root@localhost:~/gigahorse-toolchain# ./gigahorse.py examples/long_running.hex
Compiling /root/gigahorse-toolchain/logic/decompiler.dl to C++ program and executable
Warning: Variable newContext only occurs once in file transactional-context.dl at line 113
MergeContext(ctx, caller, newContext) :-
--------------------------^--------------
Warning: No rules/facts defined for relation StorageContents in file decompiler_output.dl at line 73
.decl StorageContents(addr: symbol, contents: symbol)
------^-----------------------------------------------
Warning: No rules/facts defined for relation SHA3Decompositions in file decompiler_output.dl at line 76
.decl SHA3Decompositions(addr: symbol, base1: symbol, base2: symbol, offset: symbol)
------^------------------------------------------------------------------------------
compiler error: cannot compile source file /root/gigahorse-toolchain/cache/27ac96bc0706b376ea84362bc8505794.cpp
g++ -std=c++17   -fwrapv  -DUSE_NCURSES  -O3 -DUSE_LIBZ  -DUSE_SQLITE  -fopenmp  -march=native  -std=c++17 -Wdate-time -D_FORTIFY_SOURCE=2 -o/root/gigahorse-toolchain/cache/27ac96bc0706b376ea84362bc8505794 /root/gigahorse-toolchain/cache/27ac96bc0706b376ea84362bc8505794.cpp  -ldl -lpthread -lsqlite3 -lz -lncurses -lfunctors  -I/usr/bin/../include -I/usr/bin/include
virtual memory exhausted: Cannot allocate memory
failed to compile C++ source </root/gigahorse-toolchain/cache/27ac96bc0706b376ea84362bc8505794.cpp>
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "./gigahorse.py", line 219, in compile_datalog
    assert not(process.returncode), "Compilation failed. Stopping."
AssertionError: Compilation failed. Stopping.
Traceback (most recent call last):
  File "./gigahorse.py", line 422, in <module>
    open(v, 'r') # check program exists
FileNotFoundError: [Errno 2] No such file or directory: 'decompiler_compiled'

**Comment by iliastsa** [comment]
Hi! Have you compiled the `souffle-addon` library and exported the relevant `LIBRARY_PATH` and `LD_LIBRARY_PATH` environment variables?

Also, what are your system specs? I see `virtual memory exhausted: Cannot allocate memory`, which might be related.

**Comment by darkn0mad** [comment]
I added LIBRARY_PATH and LD_LIBRARY_PATH variables but another issue still persists: gigahorse.py stalls after compilation (~ 0% cpu usage and its "analysing" forever, I tried to increase timeout in gigahorse.py, but still no improvement): 
root@localhost:~/gigahorse-toolchain# ./gigahorse.py examples/long_running.hex
Compiling /root/gigahorse-toolchain/logic/decompiler.dl to C++ program and executable
Warning: Variable newContext only occurs once in file transactional-context.dl at line 113
MergeContext(ctx, caller, newContext) :-
--------------------------^--------------
Warning: No rules/facts defined for relation StorageContents in file decompiler_output.dl at line 73
.decl StorageContents(addr: symbol, contents: symbol)
------^-----------------------------------------------
Warning: No rules/facts defined for relation SHA3Decompositions in file decompiler_output.dl at line 76
.decl SHA3Decompositions(addr: symbol, base1: symbol, base2: symbol, offset: symbol)
------^------------------------------------------------------------------------------
Processing contract names.
Setting up workers.
Analysing...
