### ISSUE TITLE
ReentrancyGuard deleted

### ISSUE THREAD

**Issue by mentalrob** [nevillegrech/gigahorse-toolchain#89]
In this commit https://github.com/nevillegrech/gigahorse-toolchain/commit/81e1c18956f07e5392fbe322d6312a34573483aa, reentrancy guard seems removed. What was the reason ? @yanniss

**Comment by yanniss** [comment]
I'm afraid I don't have a better answer than the commit subject: "Move functionality to better place". This was not decompilation functionality, so I don't see how it belongs in this repo at all.
