### ISSUE TITLE
When experimenting with example, the following error was reported

### ISSUE THREAD

**Issue by taka250** [nevillegrech/gigahorse-toolchain#90]
When experimenting with example, the following error was reported
，help

root@hecs-214309:~/work/gig/gigahorse-toolchain# ./gigahorse.py examples/long_running.hex
Compiling /root/work/gig/gigahorse-toolchain/logic/fallback_precise.dl to C++ program and executable
Compiling /root/work/gig/gigahorse-toolchain/logic/main.dl to C++ program and executable
Compiling /root/work/gig/gigahorse-toolchain/logic/fallback_scalable.dl to C++ program and executable
Compiling /root/work/gig/gigahorse-toolchain/clientlib/function_inliner.dl to C++ program and executable
Warning: No rules/facts defined for relation global.sens.MergeContextResponse in abstract_context.dl:14:9
Error: Ignored execution plan for non-recursive clause in local.dl:605:12
Warning: No rules/facts defined for relation revertCloner.Prev_Block_OriginalBlock in statement_insertor.dl:246:9
1 errors generated, evaluation aborted
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/work/gig/gigahorse-toolchain/./gigahorse.py", line 342, in compile_datalog
    assert not(process.returncode), f"Compilation for {spec} failed. Stopping."
AssertionError: Compilation for /root/work/gig/gigahorse-toolchain/logic/fallback_scalable.dl failed. Stopping.
Warning: No rules/facts defined for relation global.sens.MergeContextResponse in abstract_context.dl:14:9
Error: Ignored execution plan for non-recursive clause in local.dl:605:12
Warning: No rules/facts defined for relation revertCloner.Prev_Block_OriginalBlock in statement_insertor.dl:246:9
1 errors generated, evaluation aborted
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()

**Comment by yanniss** [comment]
Should be fixed by https://github.com/nevillegrech/gigahorse-toolchain/commit/66e0db1d9c6f72bec7e3aedb0d5a0e757c4cc909
